<?php

namespace Zerp\Training\Database\Seeders;

use Illuminate\Database\Seeder;
use Zerp\Training\Models\Training;
use Zerp\Training\Models\TrainingType;
use Zerp\Training\Models\Trainer;
use Carbon\Carbon;
use Zerp\Hrm\Models\Department;

class TrainingDemoSeeder extends Seeder
{
    public function run($userId)
    {
        if (Training::where('created_by', $userId)->exists()) {
            return;
        }
        $trainingTypeIds = TrainingType::pluck('id')->toArray();
        $trainerIds = Trainer::pluck('id')->toArray();
        
        if (empty($trainingTypeIds) || empty($trainerIds)) {
            return;
        }
        
        $trainingData = [
            [
                'title' => 'Advanced Software Development Bootcamp',
                'description' => 'Comprehensive technical training program covering modern programming languages, frameworks, and development methodologies. Participants will learn advanced coding techniques, software architecture principles, and best practices for scalable application development.',
                'training_type_id' => 1,
                'trainer_id' => 1,
                'branch_id' => 1,
                'start_time' => '09:00',
                'end_time' => '17:00',
                'location' => 'Tech Lab - Building A',
                'max_participants' => 25,
                'cost' => 2500.00,
                'status' => 'completed',
            ],
            [
                'title' => 'Executive Leadership Excellence Program',
                'description' => 'Strategic leadership development initiative designed for senior managers and executives. Focus on team building, strategic decision-making, organizational leadership, and change management in dynamic business environments.',
                'training_type_id' => 2,
                'trainer_id' => 2,
                'branch_id' => 2,
                'start_time' => '08:30',
                'end_time' => '16:30',
                'location' => 'Executive Conference Room',
                'max_participants' => 15,
                'cost' => 3500.00,
                'status' => 'completed',
            ],
            [
                'title' => 'Digital Marketing Mastery Workshop',
                'description' => 'Comprehensive digital marketing training covering SEO, social media marketing, content strategy, and analytics. Participants will learn to create effective online campaigns and measure marketing ROI.',
                'training_type_id' => 3,
                'trainer_id' => 3,
                'branch_id' => 3,
                'start_time' => '10:00',
                'end_time' => '18:00',
                'location' => 'Marketing Studio',
                'max_participants' => 30,
                'cost' => 1800.00,
                'status' => 'completed',
            ],
            [
                'title' => 'Customer Service Excellence Training',
                'description' => 'Customer-focused service training emphasizing communication skills, problem resolution, and customer satisfaction. Designed to enhance customer relationship management and service quality standards across all touchpoints.',
                'training_type_id' => 4,
                'trainer_id' => 4,
                'branch_id' => 4,
                'start_time' => '09:30',
                'end_time' => '17:30',
                'location' => 'Customer Service Training Center',
                'max_participants' => 40,
                'cost' => 1200.00,
                'status' => 'completed',
            ],
            [
                'title' => 'Project Management Professional Certification',
                'description' => 'Intensive project management training covering PMP methodologies, Agile frameworks, risk management, and project delivery best practices. Prepares participants for professional certification and advanced project leadership roles.',
                'training_type_id' => 5,
                'trainer_id' => 5,
                'branch_id' => 5,
                'start_time' => '08:00',
                'end_time' => '16:00',
                'location' => 'Project Management Institute',
                'max_participants' => 20,
                'cost' => 4200.00,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Sales Excellence and Business Development',
                'description' => 'Advanced sales training focusing on lead generation, negotiation techniques, relationship building, and revenue optimization. Includes CRM management and sales process automation for maximum effectiveness.',
                'training_type_id' => 6,
                'trainer_id' => 6,
                'branch_id' => 1,
                'start_time' => '09:00',
                'end_time' => '17:00',
                'location' => 'Sales Training Facility',
                'max_participants' => 35,
                'cost' => 2800.00,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Quality Assurance and Testing Methodologies',
                'description' => 'Comprehensive QA training covering testing frameworks, quality control processes, and continuous improvement methodologies. Ensures product excellence and maintains high standards across all deliverables.',
                'training_type_id' => 7,
                'trainer_id' => 7,
                'branch_id' => 2,
                'start_time' => '10:00',
                'end_time' => '18:00',
                'location' => 'Quality Assurance Lab',
                'max_participants' => 22,
                'cost' => 2200.00,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Financial Management and Analysis Workshop',
                'description' => 'Financial planning and analysis training covering budgeting, financial reporting, investment analysis, and cost management. Designed for finance professionals and managers requiring advanced financial skills.',
                'training_type_id' => 8,
                'trainer_id' => 8,
                'branch_id' => 3,
                'start_time' => '08:30',
                'end_time' => '16:30',
                'location' => 'Finance Training Center',
                'max_participants' => 18,
                'cost' => 3200.00,
                'status' => 'scheduled',
            ],
            [
                'title' => 'Human Resources Development Program',
                'description' => 'HR best practices training including recruitment strategies, employee engagement, performance management, and organizational development. Builds effective people management capabilities for HR professionals.',
                'training_type_id' => 9,
                'trainer_id' => 9,
                'branch_id' => 4,
                'start_time' => '09:00',
                'end_time' => '17:00',
                'location' => 'HR Development Center',
                'max_participants' => 28,
                'cost' => 2600.00,
                'status' => 'completed',
            ],
            [
                'title' => 'Professional Communication and Presentation Skills',
                'description' => 'Communication excellence training covering verbal, written, and presentation skills. Enhances interpersonal communication, public speaking abilities, and professional presentation techniques for workplace success.',
                'training_type_id' => 10,
                'trainer_id' => 10,
                'branch_id' => 5,
                'start_time' => '10:00',
                'end_time' => '18:00',
                'location' => 'Communication Skills Studio',
                'max_participants' => 32,
                'cost' => 1500.00,
                'status' => 'scheduled',
            ],
            [
                'title' => 'Data Science and Analytics Fundamentals',
                'description' => 'Data analysis and visualization training covering statistical analysis, machine learning basics, and business intelligence tools. Enables data-driven decision making and advanced analytics capabilities.',
                'training_type_id' => 11,
                'trainer_id' => 11,
                'branch_id' => 1,
                'start_time' => '09:30',
                'end_time' => '17:30',
                'location' => 'Data Science Lab',
                'max_participants' => 24,
                'cost' => 3800.00,
                'status' => 'scheduled',
            ],
            [
                'title' => 'Cybersecurity and Information Protection',
                'description' => 'Comprehensive cybersecurity training covering threat assessment, security protocols, data protection, and compliance requirements. Essential for maintaining organizational security and regulatory adherence.',
                'training_type_id' => 12,
                'trainer_id' => 12,
                'branch_id' => 2,
                'start_time' => '08:00',
                'end_time' => '16:00',
                'location' => 'Cybersecurity Training Center',
                'max_participants' => 20,
                'cost' => 4500.00,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Supply Chain and Operations Excellence',
                'description' => 'Operations optimization training focusing on supply chain management, process improvement, and operational efficiency. Covers Lean Six Sigma methodologies and cost reduction strategies.',
                'training_type_id' => 13,
                'trainer_id' => 13,
                'branch_id' => 3,
                'start_time' => '09:00',
                'end_time' => '17:00',
                'location' => 'Operations Management Center',
                'max_participants' => 26,
                'cost' => 2900.00,
                'status' => 'cancelled',
            ],
            [
                'title' => 'Innovation and Creative Problem Solving',
                'description' => 'Creative thinking and innovation training using design thinking methodologies. Encourages innovative solutions, creative workplace culture, and systematic approach to problem-solving challenges.',
                'training_type_id' => 14,
                'trainer_id' => 14,
                'branch_id' => 4,
                'start_time' => '10:00',
                'end_time' => '18:00',
                'location' => 'Innovation Lab',
                'max_participants' => 30,
                'cost' => 2100.00,
                'status' => 'cancelled',
            ],
            [
                'title' => 'Compliance and Regulatory Standards Training',
                'description' => 'Industry compliance and regulatory training covering legal obligations, industry standards, and regulatory requirements. Ensures organizational adherence to laws and maintains compliance across operations.',
                'training_type_id' => 15,
                'trainer_id' => 15,
                'branch_id' => 5,
                'start_time' => '08:30',
                'end_time' => '16:30',
                'location' => 'Compliance Training Room',
                'max_participants' => 16,
                'cost' => 3600.00,
                'status' => 'scheduled',
            ],
            [
                'title' => 'Workplace Health and Safety Management',
                'description' => 'Comprehensive safety training covering workplace safety protocols, health management systems, emergency response procedures, and safety compliance. Critical for maintaining safe working environments.',
                'training_type_id' => 16,
                'trainer_id' => 16,
                'branch_id' => 1,
                'start_time' => '09:00',
                'end_time' => '17:00',
                'location' => 'Safety Training Center',
                'max_participants' => 45,
                'cost' => 1400.00,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Strategic Business Planning Workshop',
                'description' => 'Strategic planning methodologies training covering market analysis, business development strategies, and long-term planning capabilities. Develops strategic thinking and competitive advantage planning.',
                'training_type_id' => 17,
                'trainer_id' => 17,
                'branch_id' => 2,
                'start_time' => '08:00',
                'end_time' => '16:00',
                'location' => 'Strategic Planning Suite',
                'max_participants' => 12,
                'cost' => 4800.00,
                'status' => 'scheduled',
            ],
            [
                'title' => 'Cloud Computing and DevOps Practices',
                'description' => 'Modern cloud infrastructure and DevOps training covering AWS, Azure, containerization, and continuous integration deployment methodologies. Essential for modern software development and deployment.',
                'training_type_id' => 18,
                'trainer_id' => 18,
                'branch_id' => 3,
                'start_time' => '09:30',
                'end_time' => '17:30',
                'location' => 'Cloud Computing Lab',
                'max_participants' => 22,
                'cost' => 3400.00,
                'status' => 'scheduled',
            ],
            [
                'title' => 'Product Management and Development Strategy',
                'description' => 'Product lifecycle management training covering user experience design, product strategy development, and market positioning. Essential for successful product planning and competitive market success.',
                'training_type_id' => 19,
                'trainer_id' => 19,
                'branch_id' => 4,
                'start_time' => '10:00',
                'end_time' => '18:00',
                'location' => 'Product Development Center',
                'max_participants' => 28,
                'cost' => 3100.00,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Emotional Intelligence and Leadership Skills',
                'description' => 'Emotional intelligence development training focusing on interpersonal skills, workplace relationship management, and team collaboration. Builds essential soft skills for professional success.',
                'training_type_id' => 20,
                'trainer_id' => 20,
                'branch_id' => 5,
                'start_time' => '09:00',
                'end_time' => '17:00',
                'location' => 'Leadership Development Center',
                'max_participants' => 35,
                'cost' => 2300.00,
                'status' => 'cancelled',
            ],
            [
                'title' => 'Agile and Scrum Implementation Workshop',
                'description' => 'Agile project management and Scrum framework training covering iterative development processes, team collaboration, and modern project delivery methodologies for enhanced productivity.',
                'training_type_id' => 21,
                'trainer_id' => 21,
                'branch_id' => 1,
                'start_time' => '08:30',
                'end_time' => '16:30',
                'location' => 'Agile Training Room',
                'max_participants' => 30,
                'cost' => 2700.00,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Business Intelligence and Reporting Systems',
                'description' => 'Business intelligence tools and data visualization training covering reporting systems, dashboard creation, and data-driven insights for informed business decision-making processes.',
                'training_type_id' => 22,
                'trainer_id' => 22,
                'branch_id' => 2,
                'start_time' => '09:00',
                'end_time' => '17:00',
                'location' => 'Business Intelligence Lab',
                'max_participants' => 25,
                'cost' => 3300.00,
                'status' => 'scheduled',
            ],
            [
                'title' => 'Mobile Application Development Bootcamp',
                'description' => 'Mobile app development training for iOS and Android platforms covering native and cross-platform frameworks, UI/UX design principles, and mobile optimization techniques for modern applications.',
                'training_type_id' => 23,
                'trainer_id' => 23,
                'branch_id' => 3,
                'start_time' => '10:00',
                'end_time' => '18:00',
                'location' => 'Mobile Development Studio',
                'max_participants' => 20,
                'cost' => 3900.00,
                'status' => 'scheduled',
            ],
            [
                'title' => 'E-commerce and Digital Business Strategy',
                'description' => 'E-commerce platform management and online business operations training focusing on digital marketing strategies, online sales optimization, and digital commerce success methodologies.',
                'training_type_id' => 24,
                'trainer_id' => 24,
                'branch_id' => 4,
                'start_time' => '09:30',
                'end_time' => '17:30',
                'location' => 'E-commerce Training Center',
                'max_participants' => 32,
                'cost' => 2400.00,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Time Management and Personal Productivity',
                'description' => 'Personal productivity and time management training covering workflow optimization techniques, efficiency strategies, and work-life balance for enhanced individual and team performance.',
                'training_type_id' => 25,
                'trainer_id' => 25,
                'branch_id' => 5,
                'start_time' => '08:00',
                'end_time' => '16:00',
                'location' => 'Productivity Training Room',
                'max_participants' => 40,
                'cost' => 1300.00,
                'status' => 'scheduled',
            ],
            [
                'title' => 'Advanced Negotiation and Conflict Resolution',
                'description' => 'Professional negotiation techniques and conflict resolution training covering mediation skills, business negotiation strategies, and workplace harmony management for effective business dealings.',
                'training_type_id' => 26,
                'trainer_id' => 26,
                'branch_id' => 1,
                'start_time' => '09:00',
                'end_time' => '17:00',
                'location' => 'Negotiation Skills Center',
                'max_participants' => 18,
                'cost' => 3700.00,
                'status' => 'completed',
            ],
            [
                'title' => 'Environmental Sustainability and Green Practices',
                'description' => 'Sustainable business practices training covering environmental compliance, green technology implementation, and corporate social responsibility for eco-friendly operations and environmental stewardship.',
                'training_type_id' => 27,
                'trainer_id' => 27,
                'branch_id' => 2,
                'start_time' => '10:00',
                'end_time' => '18:00',
                'location' => 'Sustainability Training Center',
                'max_participants' => 35,
                'cost' => 2000.00,
                'status' => 'cancelled',
            ],
            [
                'title' => 'International Business and Global Trade',
                'description' => 'Global business operations training covering international trade regulations, cross-cultural communication, and global market strategies. Essential for companies operating in international markets.',
                'training_type_id' => 28,
                'trainer_id' => 28,
                'branch_id' => 3,
                'start_time' => '08:30',
                'end_time' => '16:30',
                'location' => 'International Business Center',
                'max_participants' => 24,
                'cost' => 4100.00,
                'status' => 'scheduled',
            ],
            [
                'title' => 'Risk Management and Business Continuity',
                'description' => 'Risk identification and assessment training covering mitigation strategies, business continuity planning, and organizational resilience for effective risk management and crisis preparedness.',
                'training_type_id' => 29,
                'trainer_id' => 29,
                'branch_id' => 4,
                'start_time' => '09:00',
                'end_time' => '17:00',
                'location' => 'Risk Management Institute',
                'max_participants' => 16,
                'cost' => 4300.00,
                'status' => 'completed',
            ],
            [
                'title' => 'Artificial Intelligence and Machine Learning Applications',
                'description' => 'AI fundamentals and machine learning training covering practical implementation strategies, intelligent automation solutions, and AI integration for modern business applications and competitive advantage.',
                'training_type_id' => 30,
                'trainer_id' => 30,
                'branch_id' => 5,
                'start_time' => '10:00',
                'end_time' => '18:00',
                'location' => 'AI and ML Research Center',
                'max_participants' => 15,
                'cost' => 5200.00,
                'status' => 'scheduled',
            ],
        ];
        
        foreach ($trainingData as $index => $data) {
            $branchId = $data['branch_id'];
            $branchDepartments = Department::where('branch_id', $branchId)->pluck('id')->toArray();
            $departmentId = !empty($branchDepartments) ? $branchDepartments[array_rand($branchDepartments)] : 1;
            
            $startDate = Carbon::now()->subDays(180 - ($index * 6));
            $endDate = $startDate->copy()->addDays(rand(1, 5));
            if ($branchId && $departmentId) {
            Training::create([
                'title' => $data['title'],
                'description' => $data['description'],
                'training_type_id' => $data['training_type_id'],
                'trainer_id' => $data['trainer_id'],
                'branch_id' => $branchId,
                'department_id' => $departmentId,
                'start_date' => $startDate->format('Y-m-d'),
                'end_date' => $endDate->format('Y-m-d'),
                'start_time' => $data['start_time'],
                'end_time' => $data['end_time'],
                'location' => $data['location'],
                'max_participants' => $data['max_participants'],
                'cost' => $data['cost'],
                'status' => $data['status'],
                'creator_id' => 2,
                'created_by' => 2,
                'created_at' => $startDate->subHours(rand(1, 23))->subMinutes(rand(1, 59)),
                'updated_at' => $startDate->addHours(rand(1, 23))->addMinutes(rand(1, 59)),
            ]);
        }
        }
    }
}